config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  #root :to => redirect("/users/sign_in")
  root :to => "practitioners#index"

  resources :employee_examination_sessions
  resources :employees
  resources :examination_sessions do
    member do
      get 'summary'
    end
  end
  resources :workplaces
  resources :practitioners

  devise_for :users


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id           :bigint           not null, primary key
#  address      :string
#  dob          :date
#  gender       :integer
#  name         :string
#  pn           :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  national_id  :string
#  workplace_id :bigint
#
class Employee < ApplicationRecord
    enum gender: [:female, :male]

    ############### Validations ##########################

    validates :national_id, presence: true, uniqueness: true

    validates_presence_of :dob, :gender, :name

    ############### Associations #########################

    belongs_to :workplace
    has_many :employee_examination_sessions, dependent: :destroy
    has_many :examination_sessions, through: :employee_examination_sessions

    ############### Some 'helper' methods #################

    def age()
        now = Time.now.utc.to_date
        now.year - self.dob.year - ((now.month > self.dob.month || (now.month == self.dob.month && now.day >= self.dob.day)) ? 0 : 1)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.paginate(page: params[:page])
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:address, :dob, :gender, :name, :pn, :national_id, :workplace_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<!-- // Basic Horizontal form layout section start -->
<div class="row d-flex justify-content-center">

  <div class="col-md-6 col-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body">

          <%= form_with(model: employee, local: true, class: "form form-horizontal") do |form| %>
          <% if employee.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

            <ul>
              <% employee.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <div class="form-body">
            <div class="row">
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> Name </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
                      <div class="form-control-position">
                        <i class="feather icon-user"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> Date of Birth </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.date_select :dob, class: "form-control", start_year: 1950, end_year: Time.now.year  %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> Gender
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.select(:gender, options_for_select([['Male', 'male'], ['Female', 'female']]), {:prompt => 'Select Gender'}, {:class=>'custom-select'})%>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> Address
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :address, class: "form-control", placeholder: "Address" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> Personal Number
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :pn, class: "form-control", placeholder: "Personal Number" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> National ID
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :national_id, class: "form-control", placeholder: "National ID" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> Workplace
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.collection_select(:workplace_id, Workplace.all, :id, :name, {}, {:class=>'custom-select'}) %>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-md-8 offset-md-4">
                <button type="submit" class="btn btn-primary mr-1 mb-1">Submit</button>
                <button type="reset" class="btn btn-outline-warning mr-1 mb-1">Reset</button>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- // Basic Horizontal form layout section end -->

app/views/employees/edit.html.erb
<!-- Doing this to  make sure the navigation bar hightlights the correct tabs -->
<% content_for :employees do %>
active
<% end %>

<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<!-- Doing this to  make sure the navigation bar hightlights the correct tabs -->
<% content_for :employees do %>
active
<% end %>

<!-- Basic Tables start -->
<div class="row" id="basic-table">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Employees</h4>
      </div>
      <div class="card-content">
        <div class="card-body">
          <p class="card-text">All employees.</p>
          <!-- Table with outer spacing -->
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>National ID</th>
                  <th>Name</th>
                  <th>Age (YRS)</th>
                  <th>Gender</th>
                  <th>Address</th>
                  <th>Personal Number</th>
                  <th>Workplace</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @employees.each do |employee| %>
                <tr>
                  <td><%= employee.national_id %></td>
                  <td><%= employee.name %></td>
                  <td><%= employee.age %></td>
                  <td><%= employee.gender %></td>
                  <td><%= employee.address %></td>
                  <td><%= employee.pn %></td>
                  <td><%= employee.workplace.name %></td>
                  <td><%= link_to 'Show', employee %></td>
                  <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
                  <% if current_user.has_role?(:admin) %>
                  <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% end %>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <p>
            <div class="digg_pagination">
              <%= will_paginate @workplaces, :container => false %>
            </div>
          </p>
          <%= link_to '<button type="button" class="btn btn-outline-dark mr-1 mb-1">New Employee</button>'.html_safe, new_employee_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<!-- Doing this to  make sure the navigation bar hightlights the correct tabs -->
<% content_for :employees do %>
active
<% end %>

<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<!-- Doing this to  make sure the navigation bar hightlights the correct tabs -->
<% content_for :employees do %>
active
<% end %>

<!-- information start -->
<div class="row d-flex justify-content-center">
  <div class="col-md-6 col-12 ">
    <div class="card">
      <div class="card-header">
        <div class="card-title mb-2">About</div>
      </div>
      <div class="card-body">

        <div class="card-text">
          <dl class="row">
            <dt class="col-sm-3 text-right">Name</dt>
            <dd class="col-sm-9"> <%= @employee.name %></dd>
          </dl>

          <dl class="row">
            <dt class="col-sm-3 text-right">Date of Birth</dt>
            <dd class="col-sm-9"> <%= @employee.dob %></dd>
          </dl>
          <dl class="row">
            <dt class="col-sm-3 text-right">Gender</dt>
            <dd class="col-sm-9"> <%= @employee.gender %></dd>
          </dl>
          <dl class="row">
            <dt class="col-sm-3 text-right">Address</dt>
            <dd class="col-sm-9"> <%= @employee.address %></dd>
          </dl>
          <dl class="row">
            <dt class="col-sm-3 text-right">Personal Number</dt>
            <dd class="col-sm-9"> <%= @employee.pn %></dd>
          </dl>
          <dl class="row">
            <dt class="col-sm-3 text-right">NationalID</dt>
            <dd class="col-sm-9"> <%= @employee.national_id %></dd>
          </dl>
          <dl class="row">
            <dt class="col-sm-3 text-right">Workplace</dt>
            <dd class="col-sm-9"> <%= @employee.workplace.name %></dd>
          </dl>
        </div>

        <%= link_to 'Edit', edit_employee_path(@employee) %> |
        <%= link_to 'Back', employees_path %>
      </div>
    </div>
  </div>
</div>