config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  #root :to => redirect("/users/sign_in")
  root :to => "practitioners#index"

  resources :employee_examination_sessions
  resources :employees
  resources :examination_sessions do
    member do
      get 'summary'
    end
  end
  resources :workplaces
  resources :practitioners

  devise_for :users


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/examination_session.rb
# == Schema Information
#
# Table name: examination_sessions
#
#  id                                    :bigint           not null, primary key
#  abnormal_results                      :integer
#  abnormal_results_occupational_disease :integer
#  date_of_exam                          :date
#  examination_type                      :string
#  health_risk                           :string
#  recommended_for_re_deployment         :integer
#  created_at                            :datetime         not null
#  updated_at                            :datetime         not null
#  workplace_id                          :bigint
#
class ExaminationSession < ApplicationRecord
    ################ Validations #####################

    validates_presence_of :examination_type, :date_of_exam, :health_risk

    ############### Associations #########################

    belongs_to :workplace
    has_many   :employee_examination_sessions
    has_many   :employees, through: :employee_examination_sessions

    # TODO Test this List the employees registered in this examination session
    def employees
        self.employee_examination_sessions.map(&:employee)
    end

    # TODO Test this functionality, or discard if it proves unused
    def all_employees
        self.workplace.employees
    end

    # TODO Test this functionality. This func is supposed to return the users who are not in this session
    def unmarked_employees
        self.workplace.employees.where.not(id: self.employees.map(&:id))
    end

    def abnormal_results_non_occupational_disease
        self.abnormal_results.to_i - self.abnormal_results_occupational_disease.to_i
    end

    def practitioner_name
        self.workplace.practitioner.name
    end

    def practitioner_address
        self.workplace.practitioner.address
    end

    def practitioner_registration
        self.workplace.practitioner.registration
    end

    def practitioner_location
        self.workplace.practitioner.location
    end

    def practitioner_phone
        self.workplace.practitioner.phone
    end

    def practitioner_email
        self.workplace.practitioner.email
    end

    def practitioner_fax
        self.workplace.practitioner.fax
    end
end

app/controllers/examination_sessions_controller.rb
class ExaminationSessionsController < ApplicationController
  before_action :set_examination_session, only: [:show, :edit, :update, :destroy, :summary]

  # GET /examination_sessions
  # GET /examination_sessions.json
  def index
    @examination_sessions = ExaminationSession.paginate(page: params[:page])
  end

  # GET /examination_sessions/1
  # GET /examination_sessions/1.json
  def show
  end

  # GET /examination_sessions/new
  def new
    @examination_session = ExaminationSession.new
  end

  def summary
  end

  # GET /examination_sessions/1/edit
  def edit
  end

  # POST /examination_sessions
  # POST /examination_sessions.json
  def create
    @examination_session = ExaminationSession.new(examination_session_params)

    respond_to do |format|
      if @examination_session.save
        format.html { redirect_to @examination_session, notice: 'Examination session was successfully created.' }
        format.json { render :show, status: :created, location: @examination_session }
      else
        format.html { render :new }
        format.json { render json: @examination_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examination_sessions/1
  # PATCH/PUT /examination_sessions/1.json
  def update
    respond_to do |format|
      if @examination_session.update(examination_session_params)
        format.html { redirect_to @examination_session, notice: 'Examination session was successfully updated.' }
        format.json { render :show, status: :ok, location: @examination_session }
      else
        format.html { render :edit }
        format.json { render json: @examination_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examination_sessions/1
  # DELETE /examination_sessions/1.json
  def destroy
    @examination_session.destroy
    respond_to do |format|
      format.html { redirect_to examination_sessions_url, notice: 'Examination session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_examination_session
      @examination_session = ExaminationSession.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def examination_session_params
      params.require(:examination_session).permit(:date_of_exam, :examination_type, :workplace_id, :health_risk)
    end
end

app/helpers/examination_sessions_helper.rb
module ExaminationSessionsHelper
end

app/views/examination_sessions/_examination_session_details.html.erb
<!-- Basic Tables start -->
<div class="row" id="basic-table">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Showing employees of <%= examination_session.workplace.name %> that were
                    examined on
                    <%= examination_session.date_of_exam %></h4>
            </div>
            <div class="card-content">
                <div class="card-body">
                    <p class="card-text">All employees of the company owning this examination examination_session. You
                        can add them to the
                        list, all factors remaining constant, by click on the 'add' option</p>
                    <!-- Table with outer spacing -->
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>National ID</th>
                                    <th>Name</th>
                                    <th>Age (YRS)</th>
                                    <th>Gender</th>
                                    <th>Personal Number</th>
                                    <th>Status</th>
                                    <th colspan="3"></th>
                                </tr>
                            </thead>

                            <tbody>
                                <% examination_session.employees.each do |employee| %>

                                <% puts 'employee first examination_session is ' + employee.employee_examination_sessions.first.inspect %>
                                <% puts 'examination_session is ' + examination_session.inspect %>

                                <% @is_in_session = employee.employee_examination_sessions.include?(examination_session.employee_examination_sessions.last) %>
                                </td>

                                <tr>
                                    <td><%= employee.national_id %></td>
                                    <td><%= employee.name %></td>
                                    <td><%= employee.age %></td>
                                    <td><%= employee.gender %></td>
                                    <td><%= employee.pn %></td>
                                    <td>
                                        <div class="chip <%= @is_in_session? 'chip-primary' : '' %> mr-1">
                                            <div class="chip-body">
                                                <span
                                                    class="chip-text"><%= @is_in_session? 'examined' : 'unknown' %></span>
                                            </div>
                                        </div>
                                    </td>
                                    <td><%= link_to 'Show', employee %></td>
                                    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
                                    <% if current_user.has_role?(:admin) %>
                                    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %>
                                    </td>
                                    <% end %>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>


                    </div>
                    <%= link_to '<button type="button" class="btn btn-outline-dark mr-1 mb-1">New Employee Examination Session</button>'.html_safe, new_employee_examination_session_path(:examination_session_id => examination_session.id) %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/examination_sessions/_form.html.erb
<!-- // Basic Horizontal form layout section start -->
<div class="row match-height">

  <div class="col-md-6 col-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body">

          <%= form_with(model: examination_session, local: true, class: "form form-horizontal") do |form| %>
          <% if examination_session.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(examination_session.errors.count, "error") %> prohibited this examination_session from
              being saved:</h2>

            <ul>
              <% examination_session.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <div class="form-body">
            <div class="row">
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span>Date of examinations</span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.date_select :date_of_exam, class: "custom-select" %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> Examinations done
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :examination_type, class: "form-control", placeholder: "Examination Type" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-4">
                    <span>Type of risk to health
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :health_risk, class: "form-control", placeholder: "Type of risk to health" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="form-group row">
                  <div class="col-md-4">
                    <span>Abnormal Results
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :abnormal_results, class: "form-control", placeholder: "Abnormal results" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-4">
                    <span>Abnormal results: Occupational
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :abnormal_results_occupational_disease, class: "form-control", placeholder: "Abnormal results: Occupational" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-4">
                    <span>Recommended for re-deployment
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :recommended_for_re_deployment, class: "form-control", placeholder: "Recommended for re-deployment" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> Workplace
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <fieldset class="form-group">
                        <%= form.collection_select(:workplace_id, Workplace.all, :id, :name, {}, {:class=>'custom-select'}) %>
                      </fieldset>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-md-8 offset-md-4">
                <button type="submit" class="btn btn-primary mr-1 mb-1">Submit</button>
                <button type="reset" class="btn btn-outline-warning mr-1 mb-1">Reset</button>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- // Basic Horizontal form layout section end -->

app/views/examination_sessions/edit.html.erb
<!-- Doing this to  make sure the navigation bar hightlights the correct tabs -->
<% content_for :examination_sessions do %>
active
<% end %>

<h4>Edit examination session</h4>

<%= render 'form', examination_session: @examination_session %>
<%= render 'examination_session_details', examination_session: @examination_session %>

<%= link_to 'Show', @examination_session %> |
<%= link_to 'Back', examination_sessions_path %>

app/views/examination_sessions/index.html.erb
<!-- Doing this to  make sure the navigation bar hightlights the correct tabs -->
<% content_for :examination_sessions do %>
active
<% end %>

<!-- Basic Tables start -->
<div class="row" id="basic-table">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Examination Sessions</h4>
      </div>
      <div class="card-content">
        <div class="card-body">
          <p class="card-text">A list of Examination Sessions recorded in the past. You can save a examination_session
            and resume progress at a
            later time</p>
          <!-- Table with outer spacing -->
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Workplace</th>
                  <th>Examination Type</th>
                  <th colspan="4"></th>
                </tr>
              </thead>

              <tbody>
                <% @examination_sessions.each do |examination_session| %>
                <tr>
                  <td><%= examination_session.date_of_exam %></td>
                  <td><%= examination_session.workplace.name %></td>
                  <td><%= examination_session.examination_type %></td>
                  <td><%= link_to 'Show', examination_session %></td>
                  <td><%= link_to 'Edit', edit_examination_session_path(examination_session) %></td>
                  <td><%= link_to 'Summary', summary_examination_session_path(examination_session) %></td>
                  <% if current_user.has_role?(:admin) %>
                  <td><%= link_to 'Destroy', examination_session, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </td>
                  <% end %>

                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <p>
            <div class="digg_pagination">
              <%= will_paginate @workplaces, :container => false %>
            </div>
          </p>
          <%= link_to '<button type="button" class="btn btn-outline-dark mr-1 mb-1">New examination session</button>'.html_safe, new_examination_session_path %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Basic Tables end -->

app/views/examination_sessions/new.html.erb
<!-- Doing this to  make sure the navigation bar hightlights the correct tabs -->
<% content_for :examination_sessions do %>
active
<% end %>

<h1>New Examination Session</h1>

<%= render 'form', examination_session: @examination_session %>

<%= link_to 'Back', examination_sessions_path %>

app/views/examination_sessions/show.html.erb
<!-- Doing this to  make sure the navigation bar hightlights the correct tabs -->
<% content_for :examination_sessions do %>
active
<% end %>

<!-- information start -->
<div class="row match-height">
  <div class="col-md-6 col-12 ">
    <div class="card">
      <div class="card-header">
        <div class="card-title mb-2">About</div>
      </div>
      <div class="card-body">
        <div class="card-text">
          <dl class="row">
            <dt class="col-sm-3 text-right">Date of Exam</dt>
            <dd class="col-sm-9"> <%= @examination_session.date_of_exam %></dd>
          </dl>

          <dl class="row">
            <dt class="col-sm-3 text-right">Workplace</dt>
            <dd class="col-sm-9"> <%= @examination_session.workplace.name %></dd>
          </dl>
          <dl class="row">
            <dt class="col-sm-3 text-right">Examination Type</dt>
            <dd class="col-sm-9"> <%= @examination_session.examination_type %></dd>
          </dl>
        </div>

        <%= link_to 'Edit', edit_examination_session_path(@examination_session)  %> |
        <%= link_to 'Back', examination_sessions_path %>
      </div>
    </div>
  </div>
</div>

<%= render 'examination_session_details', examination_session: @examination_session %>

app/views/examination_sessions/summary.html.erb
<div class="row d-flex justify-content-center">
    <!-- Description lists horizontal -->
    <div class="">
        <div class="card">

            <div class="row d-flex justify-content-center">
                <div class="card-header">
                    <img src="/app-assets/images/logo/coa.jpg"> </div>
            </div>
            <div class="card-header">
                <h4 class="card-title"><strong>DOSH 9</strong></h4>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="card-header">
                    <h4 class="card-title">MINISTRY OF LABOUR AND SOCIAL PROTECTION STATE DEPARTMENT FOR LABOUR</h4>
                </div>

            </div>

            <div class="row d-flex justify-content-center">
                <div class="card-header">
                    <h4 class="card-title">DIRECTORATE OF OCCUPATIONAL HEALTH AND SAFETY SERVICES</h4>
                </div>
            </div>

            <div class="row d-flex justify-content-center">
                <div class="card-header">
                    <h6 class="card-title"> <small>O.S.H.A., 2007 (MEDICAL EXAMINATION RULES) 2005</small></h6>
                </div>
            </div>
            <br>
            <br>

            <div class="row d-flex justify-content-center">
                <div class="card-text">
                    <h4>SECOND SCHEDULES 6 (2)</h4>
                </div>
            </div>

            <div class="row d-flex justify-content-center">
                <div class="card-text">
                    <h4><strong>SUMMARY REPORT FORM</strong></h4>
                </div>
            </div>

            <div class="card-header">
                <p>This form should be completed by the designated health practitioner and sumitted to the director
                    within twenty one days and a copy sent to the employer</p>
            </div>

            <div class="card-content">
                <div class="card-body">
                    <div class="card-text">
                        <dl class="row">
                            <dt class="col-sm-4">Name of workplace</dt>
                            <dd class="col-sm-8"><%=  @examination_session.workplace.name %></dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-4">Workplace registration number</dt>
                            <dd class="col-sm-8"><%=  @examination_session.workplace.registration %>
                            </dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-4">Location</dt>
                            <dd class="col-sm-8 ml-auto"><%=  @examination_session.workplace.location %></dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-4">Tel</dt>
                            <dd class="col-sm-8 ml-auto"><%=  @examination_session.workplace.phone %></dd>
                        </dl>
                        <div class="row">
                            <div class="col-sm-4">
                                <dl class="row">
                                    <dt class="col-sm-4">Address</dt>
                                    <dd class="col-sm-8"><%=  @examination_session.workplace.address %> </dd>
                                </dl>
                            </div>
                            <div class="col-sm-4">
                                <dl class="row">
                                    <dt class="col-sm-4">Email</dt>
                                    <dd class="col-sm-8"> <%=  @examination_session.workplace.email %> </dd>
                                </dl>
                            </div>
                        </div>

                        <dl class="row">
                            <dt class="col-sm-4">Type of risk to health</dt>
                            <dd class="col-sm-8"><%=  @examination_session.health_risk %></dd>
                        </dl>

                        <dl class="row">
                            <dt class="col-sm-4">Number of workers exposed</dt>
                            <dd class="col-sm-8"><%=  @examination_session.employees.count %></dd>
                        </dl>

                    </div>
                    <p>RESULTS OF EXAMINATIONS</p>
                    <div class="card-text">
                        <dl class="row">
                            <dt class="col-sm-4">Number fo employees examined</dt>
                            <dd class="col-sm-8"> <%=  @examination_session.employees.count %> </dd>
                        </dl>

                        <dl class="row">
                            <dt class="col-sm-4">Number with abnormal results</dt>
                            <dd class="col-sm-8"> <%=  @examination_session.abnormal_results.to_i %> </dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-4">(a) Occupational disease</dt>
                            <dd class="col-sm-8">
                                <%=  @examination_session.abnormal_results_occupational_disease.to_i %> </dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-4">(b) Non-occupational disease</dt>
                            <dd class="col-sm-8">
                                <%=  @examination_session.abnormal_results_non_occupational_disease %>
                            </dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-5">Number of workers recommended for re-deployment</dt>
                            <dd class="col-sm-1"><%=  @examination_session.recommended_for_re_deployment %></dd>
                        </dl>

                        <p>I certify that the information given above is correct. Particulars of all workers with
                            abnormal results including those recommended for re-deployment are attached</p>

                        <dl class="row">
                            <dt class="col-sm-4">Name of designated health practitioner</dt>
                            <dd class="col-sm-8"><%=  @examination_session.practitioner_name %></dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-4">Approved regitration number</dt>
                            <dd class="col-sm-8"><%=  @examination_session.practitioner_registration %> </dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-4">Address</dt>
                            <dd class="col-sm-8"><%=  @examination_session.practitioner_address %> </dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-4">Physical address of office</dt>
                            <dd class="col-sm-8"><%=  @examination_session.practitioner_location %></dd>
                        </dl>

                        <div class="row">
                            <div class="col-sm-4">
                                <dl class="row">
                                    <dt class="col-sm-4">Tel</dt>
                                    <dd class="col-sm-8"> <%=  @examination_session.practitioner_phone %> </dd>
                                </dl>
                            </div>
                            <div class="col-sm-4">
                                <dl class="row">
                                    <dt class="col-sm-4">Fax</dt>
                                    <dd class="col-sm-8"> <%=  @examination_session.practitioner_fax %> </dd>
                                </dl>
                            </div>
                        </div>
                        <dl class="row">
                            <dt class="col-sm-4">Email</dt>
                            <dd class="col-sm-8"><%=  @examination_session.practitioner_email %> </dd>
                        </dl>

                        <div class="row">
                            <div class="col-sm-4">
                                <dl class="row">
                                    <dt class="col-sm-4">Signature</dt>
                                    <dd class="col-sm-8"> .................................................... </dd>
                                </dl>
                            </div>
                            <div class="col-sm-4">
                                <dl class="row">
                                    <dt class="col-sm-4">Date</dt>
                                    <dd class="col-sm-8"> <%=  @examination_session.date_of_exam %> </dd>
                                </dl>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>

</div>