config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  #root :to => redirect("/users/sign_in")
  root :to => "practitioners#index"

  resources :employee_examination_sessions
  resources :employees
  resources :examination_sessions do
    member do
      get 'summary'
    end
  end
  resources :workplaces
  resources :practitioners

  devise_for :users


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<!-- BEGIN: Footer-->
<footer class="footer footer-static footer-light navbar-shadow d-none">
    <p class="clearfix blue-grey lighten-2 mb-0"><span class="float-md-left d-block d-md-inline-block mt-25">COPYRIGHT
            &copy; 2020<a class="text-bold-800 grey darken-2" href="https://nightcrawler-.github.io"
                target="_blank">frederick n,</a>All rights Reserved</span><span
            class="float-md-right d-none d-md-block">Hand-crafted & Made with<i
                class="feather icon-heart pink"></i></span>
        <button class="btn btn-primary btn-icon scroll-top" type="button"><i class="feather icon-arrow-up"></i></button>
    </p>
</footer>
<!-- END: Footer-->


<!-- BEGIN: Vendor JS-->
<script src="/app-assets/vendors/js/vendors.min.js"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="/app-assets/vendors/js/ui/jquery.sticky.js"></script>
<script src="/app-assets/vendors/js/tables/ag-grid/ag-grid-community.min.noStyle.js"></script>
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="/app-assets/js/core/app-menu.min.js"></script>
<script src="/app-assets/js/core/app.min.js"></script>
<script src="/app-assets/js/scripts/components.min.js"></script>
<script src="/app-assets/js/scripts/customizer.min.js"></script>
<script src="/app-assets/js/scripts/footer.min.js"></script>
<script src="/app-assets/vendors/js/forms/select/select2.full.min.js"></script>
<script src="/app-assets/js/scripts/forms/select/form-select2.min.js"></script>
<!-- END: Theme JS-->

<!-- BEGIN: Page JS-->
<script src="/app-assets/js/scripts/pages/app-user.min.js"></script>
<script src="/app-assets/js/scripts/pages/dashboard-analytics.min.js"></script>

<!--
<script src="/app-assets/vendors/js/charts/apexcharts.min.js"></script>
-->
<!-- END: Page JS-->

app/views/shared/_head.html.erb
<!-- BEGIN: Head-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description" content="Reboot of the original legacy MedExam">
<meta name="keywords" content="medexam reboot medical records">
<meta name="author" content="Frederick Nyawaya">
<title>MedExam Content</title>
<link rel="apple-touch-icon" href="/app-assets/images/ico/apple-icon-120.png">
<link rel="shortcut icon" type="image/x-icon" href="/app-assets/images/ico/favicon.ico">
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600" rel="stylesheet">

<!-- BEGIN: Vendor CSS-->
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/vendors.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/tables/ag-grid/ag-grid.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/tables/ag-grid/ag-theme-material.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/forms/select/select2.min.css">

<!-- END: Vendor CSS-->

<!-- BEGIN: Theme CSS-->
<link rel="stylesheet" type="text/css" href="/app-assets/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/bootstrap-extended.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/colors.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/components.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/themes/dark-layout.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/themes/semi-dark-layout.min.css">

<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/menu/menu-types/horizontal-menu.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/colors/palette-gradient.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/pages/app-user.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/pages/aggrid.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/pages/dashboard-analytics.min.css">
<!-- END: Page CSS-->

<!-- BEGIN: Page LOGIN CSS-->
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/menu/menu-types/horizontal-menu.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/colors/palette-gradient.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/pages/authentication.css">
<!-- END: Page LOGIN CSS-->


<!-- BEGIN: Custom CSS-->
<link rel="stylesheet" type="text/css" href="/assets/css/style.css">
<!-- END: Custom CSS-->
<!-- END: Head-->

app/views/shared/_header.html.erb
<!-- BEGIN: Header-->
<nav class="header-navbar navbar-expand-lg navbar navbar-with-menu navbar-fixed navbar-shadow navbar-brand-center">
    <div class="navbar-header d-xl-block d-none">
        <ul class="nav navbar-nav flex-row">
            <li class="nav-item"><a class="navbar-brand" href="index-2.html">
                    <div class="brand-logo"></div>
                </a></li>
        </ul>
    </div>
    <div class="navbar-wrapper">
        <div class="navbar-container content">
            <div class="navbar-collapse" id="navbar-mobile">
                <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
                    <ul class="nav navbar-nav">
                        <li class="nav-item mobile-menu d-xl-none mr-auto"><a
                                class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i
                                    class="ficon feather icon-menu"></i></a></li>
                    </ul>
                </div>
                <ul class="nav navbar-nav float-right">
                    <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-expand"><i
                                class="ficon feather icon-maximize"></i></a></li>
                    <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link"
                            href="#" data-toggle="dropdown">
                            <div class="user-nav d-sm-flex d-none"><span
                                    class="user-name text-bold-600"><%= current_user.email %></span><span
                                    class="user-status">Available</span></div><span><img class="round"
                                    src="/app-assets/images/portrait/small/blank.png" alt="avatar" height="40"
                                    width="40"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item') %>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<!-- END: Header-->

app/views/shared/_menu.html.erb
<!-- BEGIN: Main Menu-->
<div class="horizontal-menu-wrapper">
    <div class="header-navbar navbar-expand-sm navbar navbar-horizontal floating-nav navbar-light navbar-without-dd-arrow navbar-shadow menu-border"
        role="navigation" data-menu="menu-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mr-auto"><a class="navbar-brand" href="index-2.html">
                        <div class="brand-logo"></div>
                        <h2 class="brand-text mb-0">Cafrecode - MedExam</h2>
                    </a></li>
                <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i
                            class="feather icon-x d-block d-xl-none font-medium-4 primary toggle-icon"></i><i
                            class="toggle-icon feather icon-disc font-medium-4 d-none d-xl-block collapse-toggle-icon primary"
                            data-ticon="icon-disc"></i></a></li>
            </ul>
        </div>
        <!-- Horizontal menu content-->
        <div class="navbar-container main-menu-content" data-menu="menu-container">
            <!-- include ../../../includes/mixins-->
            <ul class="nav navbar-nav" id="main-menu-navigation" data-menu="menu-navigation">
                <li class="nav-item <%= yield :dashboard %>"><a class="dropdown-toggle nav-link"
                        href="<%= dashboards_url %>"><i class="feather icon-home"></i><span
                            data-i18n="Dashboard">Dashboard</span></a>
                </li>
                <li class="nav-item <%= yield :practitioners %>"><a class="nav-link" href="<%= practitioners_url %>"><i
                            class="feather icon-monitor"></i><span data-i18n="Apps">Practitioners</span></a>
                </li>
                <li class="nav-item <%= yield :workplaces %>"><a class="nav-link" href="<%= workplaces_url %>"><i
                            class="feather icon-clipboard"></i><span data-i18n="UI Elements">Workplaces</span></a>
                </li>
                <li class="nav-item <%= yield :employees %>"><a class="nav-link" href="<%= employees_url %>"><i
                            class="feather icon-users"></i><span data-i18n="Forms &amp; Tables">Employees</span></a>
                </li>
                <li class="nav-item <%= yield :examination_sessions %>"><a class="nav-link"
                        href="<%= examination_sessions_url %>"><i class="feather icon-activity"></i><span
                            data-i18n="Pages">Examination Sessions</span></a>
                </li>
                <li class="nav-item <%= yield :employee_examination_sessions %>"><a class="nav-link"
                        href="<%= employee_examination_sessions_url %>"><i class="feather icon-file"></i><span
                            data-i18n="Pages">Employee Examination Sessions</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- END: Main Menu-->