config/routes.rb
Rails.application.routes.draw do
  resources :dashboards
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  #root :to => redirect("/users/sign_in")
  root :to => "practitioners#index"

  resources :employee_examination_sessions
  resources :employees
  resources :examination_sessions do
    member do
      get 'summary'
    end
  end
  resources :workplaces
  resources :practitioners

  devise_for :users


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/workplace.rb
# == Schema Information
#
# Table name: workplaces
#
#  id              :bigint           not null, primary key
#  address         :string
#  email           :string
#  location        :string
#  name            :string
#  phone           :string
#  registration    :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  practitioner_id :bigint
#
class Workplace < ApplicationRecord

    ################# Validations #######################
    #validates :email, email: true, uniqueness: true
    validates :name, presence: true, uniqueness: true

    #validates_presence_of :address, :location, :phone, :registration

    ############## ASSOCIATIONS #########################

    belongs_to :practitioner
    has_many :employees, dependent: :destroy
    has_many :examination_sessions
end

app/controllers/workplaces_controller.rb
class WorkplacesController < ApplicationController
  before_action :set_workplace, only: [:show, :edit, :update, :destroy]

  # GET /workplaces
  # GET /workplaces.json
  def index
    @workplaces = Workplace.paginate(page: params[:page])
  end

  # GET /workplaces/1
  # GET /workplaces/1.json
  def show
  end

  # GET /workplaces/new
  def new
    @workplace = Workplace.new
  end

  # GET /workplaces/1/edit
  def edit
  end

  # POST /workplaces
  # POST /workplaces.json
  def create
    @workplace = Workplace.new(workplace_params)

    respond_to do |format|
      if @workplace.save
        format.html { redirect_to @workplace, notice: 'Workplace was successfully created.' }
        format.json { render :show, status: :created, location: @workplace }
      else
        format.html { render :new }
        format.json { render json: @workplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workplaces/1
  # PATCH/PUT /workplaces/1.json
  def update
    respond_to do |format|
      if @workplace.update(workplace_params)
        format.html { redirect_to @workplace, notice: 'Workplace was successfully updated.' }
        format.json { render :show, status: :ok, location: @workplace }
      else
        format.html { render :edit }
        format.json { render json: @workplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workplaces/1
  # DELETE /workplaces/1.json
  def destroy
    @workplace.destroy
    respond_to do |format|
      format.html { redirect_to workplaces_url, notice: 'Workplace was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workplace
      @workplace = Workplace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workplace_params
      params.require(:workplace).permit(:address, :email, :location, :name, :phone, :registration, :practitioner_id)
    end
end

app/helpers/workplaces_helper.rb
module WorkplacesHelper
end

app/views/workplaces/_form.html.erb
<!-- // Basic Horizontal form layout section start -->
<div class="row d-flex justify-content-center">

  <div class="col-md-6 col-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body">

          <%= form_with(model: workplace, local: true, class: "form form-horizontal") do |form| %>
          <% if workplace.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(workplace.errors.count, "error") %> prohibited this workplace from being saved:</h2>

            <ul>
              <% workplace.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <div class="form-body">
            <div class="row">
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> <%= form.label :name %> </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
                      <div class="form-control-position">
                        <i class="feather icon-user"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> <%= form.label :address %>
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :address, class: "form-control", placeholder: "Address" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> Phone Number
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :phone, class: "form-control", placeholder: "Phone Number" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> <%= form.label :location %>
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :location, class: "form-control", placeholder: "Location" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> <%= form.label :registration %>
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :registration, class: "form-control", placeholder: "Registration" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> <%= form.label :email %>
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
                      <div class="form-control-position">
                        <i class="feather icon-lock"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group row">
                  <div class="col-md-4">
                    <span> <%= form.label :Practitioner %>
                    </span>
                  </div>
                  <div class="col-md-8">
                    <div class="position-relative has-icon-left">
                      <fieldset class="form-group">
                        <%= form.collection_select(:practitioner_id, Practitioner.all, :id, :name, {}, {:class=>'custom-select'}) %>
                      </fieldset>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-md-8 offset-md-4">
                <button type="submit" class="btn btn-primary mr-1 mb-1">Submit</button>
                <button type="reset" class="btn btn-outline-warning mr-1 mb-1">Reset</button>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- // Basic Horizontal form layout section end -->

app/views/workplaces/edit.html.erb
<% content_for :workplaces do %>
active
<% end %>

<h1>Editing Workplace</h1>

<%= render 'form', workplace: @workplace %>

<%= link_to 'Show', @workplace %> |
<%= link_to 'Back', workplaces_path %>

app/views/workplaces/index.html.erb
<% content_for :workplaces do %>
active
<% end %>

<!-- Basic Tables start -->
<div class="row" id="basic-table">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Workplaces</h4>
      </div>
      <div class="card-content">
        <div class="card-body">
          <p class="card-text">Available workplaces.</p>
          <!-- Table with outer spacing -->


          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Registration</th>
                  <th>Location</th>
                  <th>Phone</th>
                  <th>Address</th>
                  <th>Email</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @workplaces.each do |workplace| %>
                <tr>
                  <td><%= workplace.name %></td>
                  <td><%= workplace.registration %></td>
                  <td><%= workplace.location %></td>
                  <td><%= workplace.phone %></td>
                  <td><%= workplace.address %></td>
                  <td><%= workplace.email %></td>
                  <td><%= link_to 'Show', workplace %></td>
                  <td><%= link_to 'Edit', edit_workplace_path(workplace) %></td>
                  <% if current_user.has_role?(:admin) %>
                  <td><%= link_to 'Destroy', workplace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% end %>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <p>
            <div class="digg_pagination">
              <%= will_paginate @workplaces, :container => false %>
            </div>
          </p>
          <%= link_to '<button type="button" class="btn btn-outline-dark mr-1 mb-1">New Workplace</button>'.html_safe, new_workplace_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/workplaces/new.html.erb
<% content_for :workplaces do %>
active
<% end %>

<h1>New Workplace</h1>

<%= render 'form', workplace: @workplace %>

<%= link_to 'Back', workplaces_path %>

app/views/workplaces/show.html.erb
<!-- Doing this to  make sure the navigation bar hightlights the correct tabs -->
<% content_for :workplaces do %>
active
<% end %>
<p id="notice"><%= notice %></p>

<!-- information start -->
<div class="row d-flex justify-content-center">
  <div class="col-md-6 col-12 ">
    <div class="card">
      <div class="card-header">
        <div class="card-title mb-2">About</div>
      </div>
      <div class="card-body">
        <div class="card-text">

          <dl class="row">
            <dt class="col-sm-3 text-right">Name</dt>
            <dd class="col-sm-9"><%= @workplace.name %></dd>
          </dl>

          <dl class="row">
            <dt class="col-sm-3 text-right">Registration</dt>
            <dd class="col-sm-9"><%= @workplace.registration %></dd>
          </dl>

          <dl class="row">
            <dt class="col-sm-3 text-right">Location</dt>
            <dd class="col-sm-9"><%= @workplace.location %></dd>
          </dl>

          <dl class="row">
            <dt class="col-sm-3 text-right">Phone</dt>
            <dd class="col-sm-9"><%= @workplace.phone %></dd>
          </dl>

          <dl class="row">
            <dt class="col-sm-3 text-right">Address</dt>
            <dd class="col-sm-9"><%= @workplace.address %></dd>
          </dl>

          <dl class="row">
            <dt class="col-sm-3 text-right">Email</dt>
            <dd class="col-sm-9"><%= @workplace.email %></dd>
          </dl>
          <%= link_to 'Edit', edit_workplace_path(@workplace) %> |
          <%= link_to 'Back', workplaces_path %>
        </div>
      </div>
    </div>
  </div>
</div>